# configs/mcd_extraction.yaml

data_location: /discover/nobackup/jli30/systest/MCD_6.1/data/
data_version: '6.1'
output_path: /discover/nobackup/jli30/GraphCastMars/data/mcd_extracted/


# Time ranges
ls_range: [0, 3, 1]
lct_range: [0, 24, 6]
